# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DiceWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.DiceNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.DiceNumber.setGeometry(QtCore.QRect(80, 60, 61, 20))
        self.DiceNumber.setObjectName("DiceNumber")
        self.DiceAdd = QtWidgets.QLineEdit(self.centralwidget)
        self.DiceAdd.setGeometry(QtCore.QRect(400, 60, 91, 20))
        self.DiceAdd.setObjectName("DiceAdd")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(360, 130, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.DiceMax = QtWidgets.QLineEdit(self.centralwidget)
        self.DiceMax.setGeometry(QtCore.QRect(240, 60, 61, 20))
        self.DiceMax.setObjectName("DiceMax")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "退出程序"))
